version: '3.8'

services:
  server:
    build: ../task_5
    container_name: fcgi_container
    networks:
      - mynet

  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"
    depends_on:
      - server
    networks:
      - mynet

networks:
  mynet:
